/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type GalleryImage = {
  _id: string;
  _type: "galleryImage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  width: number;
  height: number;
  fileSize: number;
  alt?: string;
  isPublished?: boolean;
  createdAt: string;
  updatedAt?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = GalleryImage | SanityImageCrop | SanityImageHotspot | Slug | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: IMAGES_QUERY
// Query: *[_type == "galleryImage" && defined(slug.current)] | order(_createdAt desc) {    _id,    title,    slug  }
export type IMAGES_QUERYResult = Array<{
  _id: string;
  title: string;
  slug: Slug;
}>;
// Variable: IMAGE_BY_SLUG_QUERY
// Query: *[_type == "galleryImage" && slug.current == $slug][0] {    _id,    title,    slug,    description,    "url": image.asset->url,    "placeholderDataUrl": image.asset->metadata.lqip,    "width": image.asset->metadata.dimensions.width,    "height": image.asset->metadata.dimensions.height,    fileSize,    uploadedBy,    createdAt,    updatedAt  }
export type IMAGE_BY_SLUG_QUERYResult = {
  _id: string;
  title: string;
  slug: Slug;
  description: string | null;
  url: string | null;
  placeholderDataUrl: string | null;
  width: number | null;
  height: number | null;
  fileSize: number;
  uploadedBy: null;
  createdAt: string;
  updatedAt: string | null;
} | null;
// Variable: IMAGES_COUNT_QUERY
// Query: count(*[_type == "galleryImage" && defined(slug.current)])
export type IMAGES_COUNT_QUERYResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "\n  *[_type == \"galleryImage\" && defined(slug.current)] | order(_createdAt desc) {\n    _id,\n    title,\n    slug\n  }\n": IMAGES_QUERYResult;
    "\n  *[_type == \"galleryImage\" && slug.current == $slug][0] {\n    _id,\n    title,\n    slug,\n    description,\n    \"url\": image.asset->url,\n    \"placeholderDataUrl\": image.asset->metadata.lqip,\n    \"width\": image.asset->metadata.dimensions.width,\n    \"height\": image.asset->metadata.dimensions.height,\n    fileSize,\n    uploadedBy,\n    createdAt,\n    updatedAt\n  }\n": IMAGE_BY_SLUG_QUERYResult;
    "\n  count(*[_type == \"galleryImage\" && defined(slug.current)])\n": IMAGES_COUNT_QUERYResult;
  }
}
